### ISSUE TITLE
Add "Tribunal de Police francophone de Bruxelles"

### ISSUE THREAD

**Issue by PieterjanMontens** [openjusticebe/upload_ui#11]

**Comment by PieterjanMontens** [comment]
IUBEL n'intègre pas les tribunaux de police, va falloir tous les ajouter. Or il n'y a donc pas de code ECLI officiel.

En se basant sur la taxinomie employée par le spf: 
https://www.tribunaux-rechtbanken.be/fr/tribunaux-et-cours/tribunal-de-police

PRWVL
"Politierechtbank West-Vlaanderen"

PROVL
"Politierechtbank Oost-Vlaanderen"

PRANT
"Politierechtbank Antwerpen"

etc..

**Comment by tintamarre** [comment]
Resolved with https://github.com/openjusticebe/upload_ui/pull/12 🥇  (@PieterjanMontens ?)

**Comment by PieterjanMontens** [comment]
Oh yeah !
