### ISSUE TITLE
Ajout fonctionnalité OCR

### ISSUE THREAD

**Issue by PieterjanMontens** [openjusticebe/upload_ui#3]
Si le pdf est en image, passer par OCR

**Comment by tintamarre** [comment]
Un outil qui marche pas mal : https://ocrmypdf.readthedocs.io/en/latest/

Il faut implémenter une queue par contre, ça met plusieurs dizaine de secondes.

**Comment by PieterjanMontens** [comment]
Intégration direct dans TIKA: https://cwiki.apache.org/confluence/display/tika/TikaOCR

**Comment by PieterjanMontens** [comment]
C'est un issue de l'API en fait https://github.com/openjusticebe/anon_api/issues/5
Du coup je ferme.

Côté Tika, j'avais déjà installé Tesseract
